# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6ad4f5cca9b6e1274cbccbc0f3cde42db109c7ad315fe876fc0e4b2638c145aaae5d737fffe3962d88a2568c8495143a054c3e5612bc85fa5196824170c5e089

test:
  secret_key_base: a68f44a3ed0b83b0404315e4b07588aaf05287577a18bc5d17ad57de9edf969e26128aed023726b1fae8beeaab465ba6030f84f02590d2c76571231f2d6ad9f4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
